### ISSUE TITLE
Inconsistency issues with Item properties startPlace, endPlace and place

### ISSUE THREAD

**Issue by laimutisign** [gbv/jskos#126]
1. JSKOS Item properties **startPlace** and **endPlace** are defined in JSKOS [context.json](https://github.com/gbv/jskos/blob/master/context.json) schema as being the same RDF property `http://schema.org/location`, so these properties may randomly swap (startPlace <=> endPlace) when restoring JSKOS content from RDF tripples (e.g., when compacting LSON-LD content).
2. JSKOS Item property **place** is not defined in JSKOS [context.json](https://github.com/gbv/jskos/blob/master/context.json) schema, so this property is removed when compacting LSON-LD content when using JSKOS schema.
3. JSKOS [context.json](https://github.com/gbv/jskos/blob/master/context.json) schema should contain the root property @context in accordance with the 5.1 part of LSON-LD specification ([https://www.w3.org/TR/2014/REC-json-ld-20140116/#the-context](https://www.w3.org/TR/2014/REC-json-ld-20140116/#the-context)): 

> External JSON-LD context documents may contain extra information located outside of the @context key, such as documentation about the [terms](https://www.w3.org/TR/2014/REC-json-ld-20140116/#dfn-term) declared in the document. Information contained outside of the @context value is ignored when the document is used as an external JSON-LD context document.

An example JSKOS file content: [places-issue.json](https://github.com/user-attachments/files/17145244/places-issue.json)
JSKOS file after compacting LSON-LD content: [places-issue-result.json](https://github.com/user-attachments/files/17145331/places-issue-result.json) (**Note**, that property **startPlace** was changed to  **endPlace**)
Simple Java program to reproduce these results: [jskos-place.zip](https://github.com/user-attachments/files/17145337/jskos-place.zip)

**Comment by nichtich** [comment]
Thanks! I'm correcting it for the next release. `location` is http://schema.org/location., There is no perfect match for `startPlace` and `endPlace` so far. We can hijack http://schema.org/fromLocation and http://schema.org/toLocation although semantics differ slightly. The JSKOS context document is not normative anyway, so you can change it as you like.

**Comment by nichtich** [comment]
Done in release 0.5.4
