### ISSUE TITLE
allow timeintervalls for date

### ISSUE THREAD

**Issue by StiftungAusNachlass** [gbv/jskos#129]
It would be nice to allow timeintervalls for startDate, endDate (jskos "date") as described in https://en.wikipedia.org/wiki/ISO_8601#Time_intervals

Because: In DANTE there are usually never exact dates, but they often have to be estimated. That’s why “start date” is in dante actually a range. (i.e. a point in time for which the start and end are specified to express inaccuracy)

Examples:

```
jskos.startDate = 2007-03-01T13:00:00Z/2008-05-11T15:30:00Z
jskos.startDate = 2007-03-01/2008-05-11
jskos.startDate = 2007-03/2008
```

**Comment by nichtich** [comment]
This only applies to startDate, endDate, relatedDate not to created, modified, issued.

This would be solved with https://github.com/gbv/jskos/issues/35 conformance level 0 but we may allow full EDTF as well.

**Comment by StiftungAusNachlass** [comment]
Thanks! EDTF level 1 fits and allows the required ranges / intervalls. 👍

**Comment by StiftungAusNachlass** [comment]
That is ok for me as it is probably only very rarely relevant for data in controlled vocabularys anyway.

**Comment by nichtich** [comment]
Will be part of 0.6.0
