### ISSUE TITLE
Add example of pre-coordinated concept

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos#48]
A concept can also be a concept bundle:

~~~json
{
  "uri": "http://dewey.info/class/983.0616092/e22/",
  "notation": ["983.0616092"],
  "members": [
      { "uri": "http://dewey.info/class/983.0616/e22/", "notation": ["983.0616"] },
      { "uri": "http://dewey.info/class/1--092/e22/", "notation": ["1--092"] },
  ],
  "ordered": true
}
~~~

**Comment by VladimirAlexiev** [comment]
ISO 25964 has precoordination, so maybe it's better to map to that? Currently you use:
```
  "fromScheme": "void:subjectsTarget",
  "toScheme": "void:objectsTarget",
  "memberChoice": {
    "@id": "rdfs:member",
    "@container": "@list"

**Comment by nichtich** [comment]
Precoordinated concepts would not use `fromScheme`/`targetScheme` but `memberSet`/`memberList`. I don't know how ISO 25964 in RDF handles compound concepts, there have been several suggestions, e.g <http://purl.org/iso25964/skos-thes#CompoundEquivalence>. A better RDF-property than `rdfs:member` is needed. The members of a precoordinated concept are kind of `skos:broader` to the more specific concept but it's a different relationship.

**Comment by nichtich** [comment]
I added support of composed concept in 0.2.1 and summarized remaining questions to #61.
