### ISSUE TITLE
previous/next are not in SKOS

### ISSUE THREAD

**Issue by VladimirAlexiev** [gbv/jskos#59]
`previous/next` are a nice alternative for simple ordering of concepts, as opposed to using the `skos:memberList` complexity. But I'm afraid SKOS doesn't have such props:
```jsonld
"previous": {
    "@id": "http://www.w3.org/2004/02/skos/core#previous",
    "@container": "@set"
  },
  "next": {
    "@id": "http://www.w3.org/2004/02/skos/core#next",
    "@container": "@set"
  },
```
Maybe they were in a draft. If I remember correctly, maybe they were dropped to allow concepts to participate in several lists. I bet this paper [Key Choices in the Design of Simple Knowledge Organization System (SKOS)](https://arxiv.org/abs/1302.1224) (Thomas Baker, Sean Bechhofer, Antoine Isaac, Alistair Miles, Guus Schreiber, Ed Summers) has the story.

Anyway, they should be mapped to existing props. HTML Links have types `previous` & `next`.

**Comment by akuckartz** [comment]
What would be the advantages compared to the existing solutions?

**Comment by VladimirAlexiev** [comment]
See the 3 figures at http://vocab.getty.edu/doc/#skos_member_Structure: rather complex, no?
With prev/next, it would be simplified to the following:
```ttl
<aegean> skos:narrower <cycladic>, <minoan>.
<cycladic> html:next <minoan>.
<minoan> html:previous <cycladic>; skos:narrower <prepalatial>, <postpalatial>.
<prepalatial> html:next <postpalatial>.
<postpalatial> html:previous <prepalatial>.
```

**Comment by nichtich** [comment]
Thanks for catching this. Should be <http://rdf-vocabulary.ddialliance.org/xkos#previous> / <http://rdf-vocabulary.ddialliance.org/xkos#next>!

**Comment by VladimirAlexiev** [comment]
Nice! Could you give an example and motivation in the spec, contrasting it to skos:OrderedCollection and explaining the pros and cons?
Updated turtle example above.

**Comment by nichtich** [comment]
The benefit can be exemplified for instance with the Geographic concept Germany that was split and later merged again. I'll add an example based on <http://d-nb.info/gnd/4011882-4>. previous/next are inverse of each other and each forms directed acyclic graphs.

The corresponding part of JSKOS to skos:OrderedCollection is rather an [concept bundle](https://gbv.github.io/jskos/jskos.html#concept-bundles) with `memberSet` but I'm not sure whether this can cleanly be mapped to SKOS via JSON-LD.

**Comment by VladimirAlexiev** [comment]
But prev/next doesn't necessarily mean succession. The example http://vocab.getty.edu/doc/#skos_member_Structure is about periods ordered chronologically.

**Comment by nichtich** [comment]
The use case of `prev` / `next` is more practical navigation than strict formal logic. I'm closing this but an example should be added (https://github.com/gbv/jskos/issues/36)
