### ISSUE TITLE
Travis CI build fails

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos#72]
[See here](https://travis-ci.com/gbv/jskos/builds/92507660). It seems that one of the node packages (likely `jsonld`) uses `make` to build stuff which makes `npm install` fail during the Travis build.

**Comment by rutujar** [comment]
Updating to npm to version 2 

install:
  - npm install -g npm@2

**Comment by stefandesu** [comment]
> Updating to npm to version 2
> 
> install:
> 
> * npm install -g npm@2

Thanks for your contribution! Travis is using npm version 6.4.1 which is the same version I have on my local machine where `npm install` does not fail. I don't think downgrading npm to version 2 will fix the problem.
