### ISSUE TITLE
illustrative images (primary vs secondary)

### ISSUE THREAD

**Issue by VladimirAlexiev** [gbv/jskos#95]
Getty and CHIN Nomenclature (#94) have some images that illustrate concepts.
How can JSKOS represent this?

**Comment by nichtich** [comment]
See field `depiction` (mapped to `foaf:depiction`). The spec further says

> Applications MAY limit the fields `notation` and/or `depiction` to lists of a single element or ignore all preceding elements of these lists

so applications can choose to have at most one image per concept. Additional information about an image (size, license...) is out of the scope of JSKOS.

**Comment by VladimirAlexiev** [comment]
I was just about to say "stupid question" :-)
Saw it in https://gbv.github.io/jskos/context.json 
as used in https://github.com/gbv/coli-conc-licenses/blob/master/licenses.json
and rendered at https://coli-conc.gbv.de/publications/licenses/ ("Badge").

How do you handle primary vs secondary images?
- There is `foaf:img` (primary) vs `foaf:depiction` (any). foaf makes an unreasonable ontological commitment "the [img property](http://xmlns.com/foaf/spec/#term_img) is only used with representations of people (ie. instances of Person)", but I think that can be safely ignored
- I guess because jskos defines it as a `list of URI`, order must be preserved?
  - But the context says `@set`, so repositories will have trouble preserving the order...
  - (I can appreciate why you use `@set`: `rdf:List` is quite unwieldy)

```js
depiction: {
  @id: "http://xmlns.com/foaf/0.1/depiction",
  @type: "@id",
  @container: "@set"
}
```

**Comment by nichtich** [comment]
There is no distinction between primary vs secondary images. I'd expect multiple images to interchangeably illustrate a think: a client can choose whether to show any, all or none of the images listed in `depiction`. Our main client Cocoda does not support images because our vocabularies don't include images yet.

**Comment by nichtich** [comment]
Including images often comes with license requirements. Maybe it's better to change JSKOS by addition of a richer Image data type, e.g. such as [specified by IIIF](https://iiif.io/api/presentation/3.0/#requiredstatement). We could name it `image` and deprecate `depiction`.

**Comment by nichtich** [comment]
JSKOS 0.5.1 (2023-07-03) introduced a new field [media](https://gbv.github.io/jskos/jskos.html#media), this should support all needs. If not, it is better addressed in IIIF standard.
