### ISSUE TITLE
startPlace, endPlace

### ISSUE THREAD

**Issue by VladimirAlexiev** [gbv/jskos#96]
Issues about startPlace, endPlace:
- they are defined at `Concept` but I suggest to move them to `Item` to mirror startDate, endDate. This would match your 0.2.0 (2017-09-21) change: "Move startDate, endDate, relatedDate, and location from Concept to Item"
- they are missing from the context.
- perhaps because there are no appropriate schema props, see #97

**Comment by nichtich** [comment]
Thanks, done in 0.4.7.
